#! /bin/bash

kafka-topics.sh                     \
  --bootstrap-server localhost:9092 \
  --create                          \
  --topic $1                        \
  --partitions 5                    \
  --replication-factor 1
